### ISSUE TITLE
주차장 즐겨찾기 등록, 수정, 삭제, 조회 API를 구현하고 주차장 API를 수정한다

### ISSUE THREAD

**Issue by chrkb1569** [Car-Give/Backend#11]
## Description 🖊️
- 주차장 즐겨찾기 등록, 수정, 삭제, 조회 API를 구현한다.
- 기존에 구현되어 있던  주차장 API를 수정한다.

## To-do 🧑‍💻
- [ ] 주차장 즐겨찾기 등록, 수정, 삭제 API 구현
- [ ] 주차장 즐겨찾기 조회 API 구현
- [ ] 주차장 API 수정

## ETC ➕
