### ISSUE TITLE
차량, 차량 특징 카드 API를 구현하고 테스트 코드를 작성한다

### ISSUE THREAD

**Issue by chrkb1569** [Car-Give/Backend#22]
## Description 🖊️
- 차량 즐겨찾기 등록, 수정, 삭제, 조회 API를 구현한다
- 차량 특징 카드 API를 구현한다
- 누락된 테스트 코드 및 차량, 차량 특징 카드의 테스트 코드를 작성한다

## To-do 🧑‍💻
- [ ] 차량 API 구현
- [ ] 차량 특징 카드 API 구현
- [ ] 테스트 코드 작성

## ETC ➕
