### ISSUE TITLE
코드 리팩터링, 이용 기록 추가, 조회 API 구현 및 테스트 코드를 작성한다

### ISSUE THREAD

**Issue by chrkb1569** [Car-Give/Backend#29]
## Description 🖊️
- 이전 커밋에서 변경이 필요한 사항 리팩토링
- 자동차 이용 기록 추가, 조회 API 구현 및 테스트 코드 작성

## To-do 🧑‍💻
- [ ] Car 조회 API에 transform() 메서드 적용
- [ ] 중복되는 QueryResponseDto 삭제
- [ ] History API 구현
- [ ] History 테스트 코드 작성

## ETC ➕
