### ISSUE TITLE
Entity 연관 관계 설정, 회원 탈퇴, 정보 수정 기능을 구현하고 테스트 코드를 작성한다

### ISSUE THREAD

**Issue by chrkb1569** [Car-Give/Backend#47]
## Description 🖊️
- Member Entity 연관 관계 설정
- 회원 탈퇴, 회원 정보 수정 API 구현
- 회원 탈퇴, 회원 정보 수정 API 테스트 코드 작성

## To-do 🧑‍💻
- [ ] Member Entity 연관 관계 설정
- [ ] 회원 탈퇴, 회원 정보 수정 API 구현
- [ ] 회원 탈퇴, 회원 정보 수정 API 테스트 코드 작성

## ETC ➕
