### ISSUE TITLE
공지사항 및 답변 API를 구현하고, 테스트 코드를 작성한다

### ISSUE THREAD

**Issue by chrkb1569** [Car-Give/Backend#56]
## Description 🖊️
- 공지사항 API 구현
- 답변 API 구현
- 공지사항 Entity 테스트 코드 작성
- 답변 Entity 테스트 코드 작성

## To-do 🧑‍💻
- [ ] 공지사항 API 구현
- [ ] 답변 API 구현
- [ ] 공지사항 Entity 테스트 코드 작성
- [ ] 답변 Entity 테스트 코드 작성

## ETC ➕
