### ISSUE TITLE
API 명세서를 작성한다

### ISSUE THREAD

**Issue by chrkb1569** [Car-Give/Backend#62]
## Description 🖊️
- Entity의 API 명세서 작성

## To-do 🧑‍💻
- [ ] Answer Entity API 명세서 작성
- [ ] Car Entity API 명세서 작성
- [ ] FavoriteCar Entity API 명세서 작성
- [ ] FavoritePkGroup Entity API 명세서 작성
- [ ] FavoritePkInfo Entity API 명세서 작성
- [ ] History Entity API 명세서 작성
- [ ] Member Entity API 명세서 작성
- [ ] Notice Entity API 명세서 작성
- [ ] ParkingLot Entity API 명세서 작성
- [ ] Tag Entity API 명세서 작성

## ETC ➕
