### ISSUE TITLE
Enum Template 및 BaseResponse를 설정하고 Member Entity를 생성한다

### ISSUE THREAD

**Issue by Ji-Un-Gil** [Car-Give/Backend#7]
## Description 🖊️
- 다수의 Enum class가 생성될 것이므로, Enum Template 및 Converter를 생성한다
  - Converter를 사용하면 DB에 저장 시 Enum key값이 저장되지 않고 사용자가 지정한 value값으로 저장할 수 있다
- 직접 Custom한 BaseResponse 및 BaseException을 기존의 코드에서 리팩토링한다
- Member Entity를 생성한다
## To-do 🧑‍💻
- [ ] Enum Template 및 Converter 생성
- [ ] BaseResponse 및 BaseException 리팩토링 및 추가
- [ ] Member Entity 생성
- [ ] 표기법 통일을 위한 기존 디렉토리명 스타일링

## ETC ➕
