### ISSUE TITLE
자동차, 이용기록, 차량 태그 Entity를 생성하고 주차장, 즐겨찾기 Entity를 수정한다

### ISSUE THREAD

**Issue by chrkb1569** [Car-Give/Backend#8]
## Description 🖊️
- 자동차, 이용 기록, 차량 태그 Entity를 생성한다.
- 새롭게 추가하는 Entity와 연관 관계를 맺는 주차장, 즐겨찾기 Entity를 수정한다.

## To-do 🧑‍💻
- [x] 자동차 Car Entity 생성
- [x] 이용 기록 History Entity 생성
- [x] 차량 태그 Tag Entity 생성
- [x] 주차장 ParkingLot Entity 수정
- [x] 즐겨찾기 Favorite Entity 수정

## ETC ➕
